version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_DATABASE: mysqlDB
      MYSQL_USER: toor
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var