server:
    port: 8080

spring:
    application:
        name: "MS-EmailService"
    datasource:
        url: jdbc:mysql://localhost:3306/mysqlDB
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    mail:
        host: sandbox.smtp.mailtrap.io
        port: 587
        username: ****
        password: ****
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    rabbitmq:
        addresses: amqps://kkuqfjon:dKkuMliNZi-PLdClhSqqrBOMNpqPwyjD@moose.rmq.cloudamqp.com/kkuqfjon
        queue: ms.email

logging:
    level:
        root: INFO
        com.ms.email: INFO