server:
    port: 8080

spring:
    application:
        name: "MS-EmailService"
    datasource:
        url: jdbc:mysql://localhost:3306/mysqlDB
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    mail:
        host: sandbox.smtp.mailtrap.io
        port: 587
        username: SetUsername
        password: SetPassword
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true